version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/norris-deepsource/gpython"

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"